export interface ModulesTypes {
  fuel_cap: string,
  ammo: number,
  cost: number,
  fpl: number,
  hp: number,
  squares: number,
  weight: number,
  common_name: string,
  type: string,
  crew: number,
  mounting: string,
  fuel_rate: number,
  width: number,
  thrust: number,
  firewpower: number,
  id: string,
  energy: number,
  height: number,
}
